name: "Render Classics work"
description: "Render a work for Warhorn Classics..."

runs: 
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2' # The R version to download (if necessary) and use.

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.14.2'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX
          TINYTEX_VERSION: 2021.11

      - name: Install renv
        run: |
          Rscript -e 'install.packages(c("renv"))'
        shell: bash

          
      - name: Install rmarkdown & bookdown
        run: |
          Rscript -e 'renv::install("bookdown@0.24")'
          Rscript -e 'renv::install("rmarkdown@2.11")'
        shell: bash

#        run: Rscript -e 'renv::restore()'
#        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'


#      - name: Query dependencies
#        run: |
#          install.packages('remotes')
#          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
#          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
#        shell: Rscript {0}

#      - name: Install OS dependencies
#        run: |
#          brew update
#          brew install --cask xquartz
#          brew install --cask calibre

#      - name: Install phamtomJS for webshot
#        run: |
#          remotes::install_cran("webshot")
#          webshot::install_phantomjs()
#        shell: Rscript {0}

#      - name: Install R dependencies for bookdown
#        run: |
#          remotes::install_deps(dependencies = TRUE)
#        shell: Rscript {0}

#      - name: Install bookdown package
#        run: xfun::install_dir(".")
#        shell: Rscript {0}

#      - name: Session info
#        run: |
#          options(width = 100)
#          remotes::install_cran("sessioninfo")
#          pkgs <- installed.packages()[, "Package"]
#          sessioninfo::session_info(pkgs, include_base = TRUE)
#          rmarkdown::find_pandoc()
#        shell: Rscript {0}

      - name: Clone template files
        run: git clone https://github.com/warhornmedia/classics-template-files.git
        shell: bash

      - name: Run Build Script
        run: build_script.sh
        shell: bash
