name: "Build a bookdown book"
description: "Render a book, conditional on which formats are specified in bookdown"

runs: 
  using: "composite"
  steps:
      - name: Add path to build script
        run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash
        
      - name: Run Build Script
        run: build_script.sh
        shell: bash

      - name: Upload book folder for debug
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: book-dir
          path: ./